name: Readme Stuff

on:
  push:
    branches:
      - main

jobs:
  contrib-readme-job:
    runs-on: ubuntu-latest
    name: A job to automate contrib in readme
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Contribute List
        uses: siiway/contributors-readme-action@v2.3.11
        env:
          GITHUB_TOKEN: ${{ secrets.CONTRIBUTORS_BOT_SECRET }}
        with:
          image_size: 80
          use_username: true
          commit_message: "[automatic] 更新 readme contrib 列表"
          pr_title_on_protected: "[automatic] 更新 readme contrib 列表"
